# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dev\overtime-management\scheduleWidgetSuper.ui'
#
# Created: Thu Sep 21 23:50:01 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(QtGui.QWidget):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1169, 801)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(50, 100, 1081, 651))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtGui.QLabel(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBox = QtGui.QComboBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setModelColumn(0)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.entry_list = QtGui.QTreeWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_list.sizePolicy().hasHeightForWidth())
        self.entry_list.setSizePolicy(sizePolicy)
        self.entry_list.setMaximumSize(QtCore.QSize(250, 16777215))
        self.entry_list.setSizeIncrement(QtCore.QSize(0, 0))
        self.entry_list.setBaseSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.entry_list.setFont(font)
        self.entry_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.entry_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.entry_list.setAlternatingRowColors(True)
        self.entry_list.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.entry_list.setIndentation(20)
        self.entry_list.setRootIsDecorated(True)
        self.entry_list.setUniformRowHeights(False)
        self.entry_list.setAllColumnsShowFocus(False)
        self.entry_list.setHeaderHidden(False)
        self.entry_list.setObjectName(_fromUtf8("entry_list"))
        item_0 = QtGui.QTreeWidgetItem(self.entry_list)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.horizontalLayout.addWidget(self.entry_list)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.period1 = QtGui.QTableWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.period1.sizePolicy().hasHeightForWidth())
        self.period1.setSizePolicy(sizePolicy)
        self.period1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.period1.setBaseSize(QtCore.QSize(0, 0))
        self.period1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.period1.setLineWidth(1)
        self.period1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.period1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.period1.setAutoScrollMargin(16)
        self.period1.setWordWrap(True)
        self.period1.setCornerButtonEnabled(False)
        self.period1.setColumnCount(10)
        self.period1.setObjectName(_fromUtf8("period1"))
        self.period1.setRowCount(0)
        self.period1.horizontalHeader().setVisible(True)
        self.period1.horizontalHeader().setCascadingSectionResizes(False)
        self.period1.horizontalHeader().setHighlightSections(False)
        self.period1.horizontalHeader().setMinimumSectionSize(21)
        self.period1.horizontalHeader().setSortIndicatorShown(False)
        self.period1.verticalHeader().setVisible(False)
        self.period1.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.period1)
        self.period2 = QtGui.QTableWidget(self.widget)
        self.period2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.period2.sizePolicy().hasHeightForWidth())
        self.period2.setSizePolicy(sizePolicy)
        self.period2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.period2.setBaseSize(QtCore.QSize(0, 0))
        self.period2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.period2.setLineWidth(1)
        self.period2.setMidLineWidth(0)
        self.period2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.period2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.period2.setAutoScrollMargin(16)
        self.period2.setColumnCount(10)
        self.period2.setObjectName(_fromUtf8("period2"))
        self.period2.setRowCount(0)
        self.period2.horizontalHeader().setHighlightSections(False)
        self.period2.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.period2)
        self.schedule = QtGui.QTableWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule.sizePolicy().hasHeightForWidth())
        self.schedule.setSizePolicy(sizePolicy)
        self.schedule.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.schedule.setFont(font)
        self.schedule.setFrameShadow(QtGui.QFrame.Sunken)
        self.schedule.setAlternatingRowColors(True)
        self.schedule.setShowGrid(False)
        self.schedule.setGridStyle(QtCore.Qt.SolidLine)
        self.schedule.setRowCount(10)
        self.schedule.setColumnCount(10)
        self.schedule.setObjectName(_fromUtf8("schedule"))
        self.schedule.horizontalHeader().setVisible(False)
        self.schedule.horizontalHeader().setHighlightSections(False)
        self.schedule.verticalHeader().setVisible(False)
        self.schedule.verticalHeader().setStretchLastSection(False)
        self.schedule.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.verticalLayout.addWidget(self.schedule)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.label.setText(_translate("Form", "显示周期", None))
        self.comboBox.setItemText(0, _translate("Form", "月", None))
        self.comboBox.setItemText(1, _translate("Form", "周", None))
        self.comboBox.setItemText(2, _translate("Form", "日", None))
        self.entry_list.headerItem().setText(0, _translate("Form", "项目列表", None))
        __sortingEnabled = self.entry_list.isSortingEnabled()
        self.entry_list.setSortingEnabled(False)
        self.entry_list.topLevelItem(0).setText(0, _translate("Form", "项目1", None))
        self.entry_list.topLevelItem(0).child(0).setText(0, _translate("Form", "展项1", None))
        self.entry_list.topLevelItem(0).child(0).child(0).setText(0, _translate("Form", "任务1", None))
        self.entry_list.topLevelItem(0).child(1).setText(0, _translate("Form", "展项2", None))
        self.entry_list.topLevelItem(0).child(1).child(0).setText(0, _translate("Form", "任务2", None))
        self.entry_list.setSortingEnabled(__sortingEnabled)

