# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dev\overtime-management\ui_derpartment_manager.ui'
#
# Created: Thu Sep 14 00:22:16 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(QtGui.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(700, 700)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(620, 600))
        MainWindow.setMaximumSize(QtCore.QSize(700, 700))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 80, 661, 581))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.frame_2 = QtGui.QFrame(self.tab1)
        self.frame_2.setGeometry(QtCore.QRect(7, 12, 641, 521))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.widget = QtGui.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(5, 10, 631, 506))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_3 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.project_name = QtGui.QLineEdit(self.widget)
        self.project_name.setMinimumSize(QtCore.QSize(0, 25))
        self.project_name.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.project_name.setFont(font)
        self.project_name.setObjectName(_fromUtf8("project_name"))
        self.horizontalLayout_2.addWidget(self.project_name)
        self.add_project_btn = QtGui.QPushButton(self.widget)
        self.add_project_btn.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_project_btn.setFont(font)
        self.add_project_btn.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/plus2.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_project_btn.setIcon(icon)
        self.add_project_btn.setIconSize(QtCore.QSize(30, 30))
        self.add_project_btn.setObjectName(_fromUtf8("add_project_btn"))
        self.horizontalLayout_2.addWidget(self.add_project_btn)
        self.delete_project_btn = QtGui.QPushButton(self.widget)
        self.delete_project_btn.setMinimumSize(QtCore.QSize(0, 20))
        self.delete_project_btn.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_project_btn.setFont(font)
        self.delete_project_btn.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/minus.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_project_btn.setIcon(icon1)
        self.delete_project_btn.setIconSize(QtCore.QSize(30, 30))
        self.delete_project_btn.setObjectName(_fromUtf8("delete_project_btn"))
        self.horizontalLayout_2.addWidget(self.delete_project_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.project_list = QtGui.QListWidget(self.widget)
        self.project_list.setAutoFillBackground(False)
        self.project_list.setFrameShape(QtGui.QFrame.StyledPanel)
        self.project_list.setObjectName(_fromUtf8("project_list"))
        self.verticalLayout.addWidget(self.project_list)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_4 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.subproject_name = QtGui.QLineEdit(self.widget)
        self.subproject_name.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subproject_name.setFont(font)
        self.subproject_name.setObjectName(_fromUtf8("subproject_name"))
        self.horizontalLayout_6.addWidget(self.subproject_name)
        self.add_subproject_btn = QtGui.QPushButton(self.widget)
        self.add_subproject_btn.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_subproject_btn.setFont(font)
        self.add_subproject_btn.setText(_fromUtf8(""))
        self.add_subproject_btn.setIcon(icon)
        self.add_subproject_btn.setIconSize(QtCore.QSize(30, 30))
        self.add_subproject_btn.setObjectName(_fromUtf8("add_subproject_btn"))
        self.horizontalLayout_6.addWidget(self.add_subproject_btn)
        self.delete_subproject_btn = QtGui.QPushButton(self.widget)
        self.delete_subproject_btn.setMinimumSize(QtCore.QSize(0, 20))
        self.delete_subproject_btn.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_subproject_btn.setFont(font)
        self.delete_subproject_btn.setText(_fromUtf8(""))
        self.delete_subproject_btn.setIcon(icon1)
        self.delete_subproject_btn.setIconSize(QtCore.QSize(30, 30))
        self.delete_subproject_btn.setObjectName(_fromUtf8("delete_subproject_btn"))
        self.horizontalLayout_6.addWidget(self.delete_subproject_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.subproject_list = QtGui.QListWidget(self.widget)
        self.subproject_list.setObjectName(_fromUtf8("subproject_list"))
        self.verticalLayout_2.addWidget(self.subproject_list)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_8 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_4.addWidget(self.label_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(3)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.task_name = QtGui.QLineEdit(self.widget)
        self.task_name.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.task_name.setFont(font)
        self.task_name.setObjectName(_fromUtf8("task_name"))
        self.horizontalLayout_9.addWidget(self.task_name)
        self.add_task_btn = QtGui.QPushButton(self.widget)
        self.add_task_btn.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_task_btn.setFont(font)
        self.add_task_btn.setText(_fromUtf8(""))
        self.add_task_btn.setIcon(icon)
        self.add_task_btn.setIconSize(QtCore.QSize(30, 30))
        self.add_task_btn.setObjectName(_fromUtf8("add_task_btn"))
        self.horizontalLayout_9.addWidget(self.add_task_btn)
        self.delete_task_btn = QtGui.QPushButton(self.widget)
        self.delete_task_btn.setMinimumSize(QtCore.QSize(0, 20))
        self.delete_task_btn.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_task_btn.setFont(font)
        self.delete_task_btn.setText(_fromUtf8(""))
        self.delete_task_btn.setIcon(icon1)
        self.delete_task_btn.setIconSize(QtCore.QSize(30, 30))
        self.delete_task_btn.setObjectName(_fromUtf8("delete_task_btn"))
        self.horizontalLayout_9.addWidget(self.delete_task_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.task_list_ = QtGui.QListWidget(self.widget)
        self.task_list_.setObjectName(_fromUtf8("task_list_"))
        self.verticalLayout_4.addWidget(self.task_list_)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.widget1 = QtGui.QWidget(self.tab)
        self.widget1.setGeometry(QtCore.QRect(10, 15, 641, 521))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.frame_3 = QtGui.QFrame(self.widget1)
        self.frame_3.setMaximumSize(QtCore.QSize(170, 16777215))
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.frame_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(4, 5, 166, 501))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lineEdit = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 25))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_7.addWidget(self.lineEdit)
        self.add_member_btn = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.add_member_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.add_member_btn.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_member_btn.setFont(font)
        self.add_member_btn.setText(_fromUtf8(""))
        self.add_member_btn.setIcon(icon)
        self.add_member_btn.setIconSize(QtCore.QSize(30, 30))
        self.add_member_btn.setObjectName(_fromUtf8("add_member_btn"))
        self.horizontalLayout_7.addWidget(self.add_member_btn)
        self.delete_member_btn = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.delete_member_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.delete_member_btn.setMaximumSize(QtCore.QSize(30, 30))
        self.delete_member_btn.setText(_fromUtf8(""))
        self.delete_member_btn.setIcon(icon1)
        self.delete_member_btn.setIconSize(QtCore.QSize(30, 30))
        self.delete_member_btn.setObjectName(_fromUtf8("delete_member_btn"))
        self.horizontalLayout_7.addWidget(self.delete_member_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.member_list = QtGui.QListWidget(self.verticalLayoutWidget_3)
        self.member_list.setObjectName(_fromUtf8("member_list"))
        self.verticalLayout_3.addWidget(self.member_list)
        self.horizontalLayout_12.addWidget(self.frame_3)
        self.frame = QtGui.QFrame(self.widget1)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.widget2 = QtGui.QWidget(self.frame)
        self.widget2.setGeometry(QtCore.QRect(5, 5, 456, 501))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_10 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_6.addWidget(self.label_10)
        self.task_tree = QtGui.QTreeView(self.widget2)
        self.task_tree.setObjectName(_fromUtf8("task_tree"))
        self.verticalLayout_6.addWidget(self.task_tree)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_11 = QtGui.QLabel(self.widget2)
        self.label_11.setMinimumSize(QtCore.QSize(300, 0))
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        self.assign_btn = QtGui.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.assign_btn.setFont(font)
        self.assign_btn.setObjectName(_fromUtf8("assign_btn"))
        self.horizontalLayout_10.addWidget(self.assign_btn)
        self.unassign_btn = QtGui.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.unassign_btn.setFont(font)
        self.unassign_btn.setObjectName(_fromUtf8("unassign_btn"))
        self.horizontalLayout_10.addWidget(self.unassign_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.widget2)
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Raised)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setMargin(0)
        self.label.setIndent(3)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.assigned_task = QtGui.QListWidget(self.widget2)
        self.assigned_task.setObjectName(_fromUtf8("assigned_task"))
        self.verticalLayout_5.addWidget(self.assigned_task)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_12 = QtGui.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setIndent(3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_7.addWidget(self.label_12)
        self.task_desc = QtGui.QTextEdit(self.widget2)
        self.task_desc.setObjectName(_fromUtf8("task_desc"))
        self.verticalLayout_7.addWidget(self.task_desc)
        self.horizontalLayout_11.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12.addWidget(self.frame)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.query = QtGui.QPushButton(self.tab2)
        self.query.setGeometry(QtCore.QRect(460, 360, 100, 40))
        self.query.setMinimumSize(QtCore.QSize(100, 40))
        self.query.setObjectName(_fromUtf8("query"))
        self.layoutWidget = QtGui.QWidget(self.tab2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 363, 32))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setSpacing(15)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(40, 30))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.query_fromdate = QtGui.QDateEdit(self.layoutWidget)
        self.query_fromdate.setMinimumSize(QtCore.QSize(0, 30))
        self.query_fromdate.setMaximumSize(QtCore.QSize(16777215, 30))
        self.query_fromdate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.query_fromdate.setObjectName(_fromUtf8("query_fromdate"))
        self.horizontalLayout_4.addWidget(self.query_fromdate)
        self.label_6 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(30, 30))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setMidLineWidth(0)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.query_todate = QtGui.QDateEdit(self.layoutWidget)
        self.query_todate.setMinimumSize(QtCore.QSize(0, 30))
        self.query_todate.setMaximumSize(QtCore.QSize(16777215, 30))
        self.query_todate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.query_todate.setObjectName(_fromUtf8("query_todate"))
        self.horizontalLayout_4.addWidget(self.query_todate)
        self.layoutWidget1 = QtGui.QWidget(self.tab2)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 160, 531, 32))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(80, 0))
        self.label_7.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.query_project = QtGui.QComboBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.query_project.sizePolicy().hasHeightForWidth())
        self.query_project.setSizePolicy(sizePolicy)
        self.query_project.setMinimumSize(QtCore.QSize(0, 30))
        self.query_project.setMaximumSize(QtCore.QSize(16777215, 30))
        self.query_project.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.query_project.setObjectName(_fromUtf8("query_project"))
        self.query_project.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.query_project)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.tab2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 90, 261, 36))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.comboBox = QtGui.QComboBox(self.horizontalLayoutWidget_3)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.comboBox)
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.layoutWidget2 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 10, 266, 61))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.dep_line = QtGui.QComboBox(self.layoutWidget2)
        self.dep_line.setEnabled(False)
        self.dep_line.setMinimumSize(QtCore.QSize(200, 30))
        self.dep_line.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dep_line.setEditable(False)
        self.dep_line.setObjectName(_fromUtf8("dep_line"))
        self.dep_line.addItem(_fromUtf8(""))
        self.dep_line.addItem(_fromUtf8(""))
        self.dep_line.addItem(_fromUtf8(""))
        self.dep_line.addItem(_fromUtf8(""))
        self.dep_line.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.dep_line)
        self.dep_edit = QtGui.QPushButton(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dep_edit.sizePolicy().hasHeightForWidth())
        self.dep_edit.setSizePolicy(sizePolicy)
        self.dep_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.dep_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(9)
        self.dep_edit.setFont(font)
        self.dep_edit.setObjectName(_fromUtf8("dep_edit"))
        self.horizontalLayout.addWidget(self.dep_edit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "加班申请", None))
        self.label_3.setText(_translate("MainWindow", "项目列表", None))
        self.label_4.setText(_translate("MainWindow", "展项列表", None))
        self.label_8.setText(_translate("MainWindow", "任务列表", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "项目管理", None))
        self.label_9.setText(_translate("MainWindow", "成员列表", None))
        self.label_10.setText(_translate("MainWindow", "所有任务", None))
        self.assign_btn.setText(_translate("MainWindow", "分配任务", None))
        self.unassign_btn.setText(_translate("MainWindow", "取消分配", None))
        self.label.setText(_translate("MainWindow", "已分配任务", None))
        self.label_12.setText(_translate("MainWindow", "任务描述", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "成员管理", None))
        self.query.setText(_translate("MainWindow", "开始查询", None))
        self.label_5.setText(_translate("MainWindow", "从", None))
        self.query_fromdate.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.label_6.setText(_translate("MainWindow", "至", None))
        self.query_todate.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.label_7.setText(_translate("MainWindow", "查询项目", None))
        self.query_project.setItemText(0, _translate("MainWindow", "*", None))
        self.label_2.setText(_translate("MainWindow", "查询成员", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "*", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "加班统计", None))
        self.dep_line.setItemText(0, _translate("MainWindow", "三维动画", None))
        self.dep_line.setItemText(1, _translate("MainWindow", "投标动画", None))
        self.dep_line.setItemText(2, _translate("MainWindow", "二维动画", None))
        self.dep_line.setItemText(3, _translate("MainWindow", "平面设计", None))
        self.dep_line.setItemText(4, _translate("MainWindow", "编导", None))
        self.dep_edit.setText(_translate("MainWindow", "更改", None))

