# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Dev\overtime-management\ui_department_manager2.ui'
#
# Created: Thu Sep 14 19:10:32 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(QtGui.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1200, 896)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(620, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 900))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle(_fromUtf8(""))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 80, 1169, 765))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.frame_2 = QtGui.QFrame(self.tab1)
        self.frame_2.setGeometry(QtCore.QRect(7, 8, 1149, 721))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.widget = QtGui.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(7, 12, 1129, 701))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_28.setMargin(0)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_3 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_14.addWidget(self.label_3)
        self.project_list = QtGui.QTableWidget(self.widget)
        self.project_list.setAutoFillBackground(False)
        self.project_list.setFrameShape(QtGui.QFrame.StyledPanel)
        self.project_list.setColumnCount(2)
        self.project_list.setObjectName(_fromUtf8("project_list"))
        self.project_list.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.project_list.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.project_list.setHorizontalHeaderItem(1, item)
        self.project_list.horizontalHeader().setVisible(False)
        self.project_list.horizontalHeader().setDefaultSectionSize(150)
        self.project_list.horizontalHeader().setHighlightSections(True)
        self.project_list.horizontalHeader().setMinimumSectionSize(150)
        self.project_list.horizontalHeader().setStretchLastSection(True)
        self.project_list.verticalHeader().setDefaultSectionSize(30)
        self.project_list.verticalHeader().setHighlightSections(False)
        self.project_list.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout_14.addWidget(self.project_list)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_21 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_2.addWidget(self.label_21)
        self.project_name = QtGui.QLineEdit(self.widget)
        self.project_name.setMinimumSize(QtCore.QSize(0, 25))
        self.project_name.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.project_name.setFont(font)
        self.project_name.setObjectName(_fromUtf8("project_name"))
        self.horizontalLayout_2.addWidget(self.project_name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_22 = QtGui.QLabel(self.widget)
        self.label_22.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_20.addWidget(self.label_22)
        self.dateEdit = QtGui.QDateEdit(self.widget)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_20.addWidget(self.dateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_23 = QtGui.QLabel(self.widget)
        self.label_23.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_21.addWidget(self.label_23)
        self.dateEdit_2 = QtGui.QDateEdit(self.widget)
        self.dateEdit_2.setObjectName(_fromUtf8("dateEdit_2"))
        self.horizontalLayout_21.addWidget(self.dateEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.label_24 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout.addWidget(self.label_24)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.widget)
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.add_project_btn = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_project_btn.sizePolicy().hasHeightForWidth())
        self.add_project_btn.setSizePolicy(sizePolicy)
        self.add_project_btn.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_project_btn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Users/Administrator/.designer/backup/icons/plus2.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_project_btn.setIcon(icon)
        self.add_project_btn.setIconSize(QtCore.QSize(30, 30))
        self.add_project_btn.setObjectName(_fromUtf8("add_project_btn"))
        self.horizontalLayout_19.addWidget(self.add_project_btn)
        self.delete_project_btn = QtGui.QPushButton(self.widget)
        self.delete_project_btn.setMinimumSize(QtCore.QSize(0, 25))
        self.delete_project_btn.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.delete_project_btn.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Users/Administrator/.designer/backup/icons/minus.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_project_btn.setIcon(icon1)
        self.delete_project_btn.setIconSize(QtCore.QSize(30, 30))
        self.delete_project_btn.setObjectName(_fromUtf8("delete_project_btn"))
        self.horizontalLayout_19.addWidget(self.delete_project_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.verticalLayout_15.addLayout(self.verticalLayout)
        self.horizontalLayout_28.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_4 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_16.addWidget(self.label_4)
        self.subproject_list = QtGui.QTableWidget(self.widget)
        self.subproject_list.setColumnCount(2)
        self.subproject_list.setObjectName(_fromUtf8("subproject_list"))
        self.subproject_list.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.subproject_list.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.subproject_list.setHorizontalHeaderItem(1, item)
        self.subproject_list.horizontalHeader().setDefaultSectionSize(150)
        self.subproject_list.horizontalHeader().setMinimumSectionSize(200)
        self.subproject_list.horizontalHeader().setStretchLastSection(True)
        self.subproject_list.verticalHeader().setHighlightSections(False)
        self.verticalLayout_16.addWidget(self.subproject_list)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_25 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_24.addWidget(self.label_25)
        self.subproject_name = QtGui.QLineEdit(self.widget)
        self.subproject_name.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subproject_name.setFont(font)
        self.subproject_name.setObjectName(_fromUtf8("subproject_name"))
        self.horizontalLayout_24.addWidget(self.subproject_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_29 = QtGui.QLabel(self.widget)
        self.label_29.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_3.addWidget(self.label_29)
        self.comboBox = QtGui.QComboBox(self.widget)
        self.comboBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_26 = QtGui.QLabel(self.widget)
        self.label_26.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_22.addWidget(self.label_26)
        self.dateEdit_3 = QtGui.QDateEdit(self.widget)
        self.dateEdit_3.setObjectName(_fromUtf8("dateEdit_3"))
        self.horizontalLayout_22.addWidget(self.dateEdit_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_27 = QtGui.QLabel(self.widget)
        self.label_27.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_23.addWidget(self.label_27)
        self.dateEdit_4 = QtGui.QDateEdit(self.widget)
        self.dateEdit_4.setObjectName(_fromUtf8("dateEdit_4"))
        self.horizontalLayout_23.addWidget(self.dateEdit_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        self.label_28 = QtGui.QLabel(self.widget)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_2.addWidget(self.label_28)
        self.plainTextEdit_2 = QtGui.QPlainTextEdit(self.widget)
        self.plainTextEdit_2.setObjectName(_fromUtf8("plainTextEdit_2"))
        self.verticalLayout_2.addWidget(self.plainTextEdit_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.add_subproject_btn = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_subproject_btn.sizePolicy().hasHeightForWidth())
        self.add_subproject_btn.setSizePolicy(sizePolicy)
        self.add_subproject_btn.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_subproject_btn.setFont(font)
        self.add_subproject_btn.setIcon(icon)
        self.add_subproject_btn.setIconSize(QtCore.QSize(30, 30))
        self.add_subproject_btn.setObjectName(_fromUtf8("add_subproject_btn"))
        self.horizontalLayout_6.addWidget(self.add_subproject_btn)
        self.delete_subproject_btn = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_subproject_btn.sizePolicy().hasHeightForWidth())
        self.delete_subproject_btn.setSizePolicy(sizePolicy)
        self.delete_subproject_btn.setMinimumSize(QtCore.QSize(0, 20))
        self.delete_subproject_btn.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.delete_subproject_btn.setFont(font)
        self.delete_subproject_btn.setIcon(icon1)
        self.delete_subproject_btn.setIconSize(QtCore.QSize(30, 30))
        self.delete_subproject_btn.setObjectName(_fromUtf8("delete_subproject_btn"))
        self.horizontalLayout_6.addWidget(self.delete_subproject_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout_16.addLayout(self.verticalLayout_2)
        self.horizontalLayout_28.addLayout(self.verticalLayout_16)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_8 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_11.addWidget(self.label_8)
        self.task_list = QtGui.QTableWidget(self.widget)
        self.task_list.setObjectName(_fromUtf8("task_list"))
        self.task_list.setColumnCount(2)
        self.task_list.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.task_list.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.task_list.setHorizontalHeaderItem(1, item)
        self.task_list.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_11.addWidget(self.task_list)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_19 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_25.addWidget(self.label_19)
        self.task_name = QtGui.QLineEdit(self.widget)
        self.task_name.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.task_name.setFont(font)
        self.task_name.setObjectName(_fromUtf8("task_name"))
        self.horizontalLayout_25.addWidget(self.task_name)
        self.verticalLayout_11.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_30 = QtGui.QLabel(self.widget)
        self.label_30.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_26.addWidget(self.label_30)
        self.dateEdit_5 = QtGui.QDateEdit(self.widget)
        self.dateEdit_5.setObjectName(_fromUtf8("dateEdit_5"))
        self.horizontalLayout_26.addWidget(self.dateEdit_5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_31 = QtGui.QLabel(self.widget)
        self.label_31.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_27.addWidget(self.label_31)
        self.dateEdit_6 = QtGui.QDateEdit(self.widget)
        self.dateEdit_6.setObjectName(_fromUtf8("dateEdit_6"))
        self.horizontalLayout_27.addWidget(self.dateEdit_6)
        self.verticalLayout_11.addLayout(self.horizontalLayout_27)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_20 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_4.addWidget(self.label_20)
        self.task_description = QtGui.QTextEdit(self.widget)
        self.task_description.setObjectName(_fromUtf8("task_description"))
        self.verticalLayout_4.addWidget(self.task_description)
        self.verticalLayout_11.addLayout(self.verticalLayout_4)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.add_task_btn = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_task_btn.sizePolicy().hasHeightForWidth())
        self.add_task_btn.setSizePolicy(sizePolicy)
        self.add_task_btn.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_task_btn.setFont(font)
        self.add_task_btn.setObjectName(_fromUtf8("add_task_btn"))
        self.horizontalLayout_9.addWidget(self.add_task_btn)
        self.update_task_btn = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_task_btn.sizePolicy().hasHeightForWidth())
        self.update_task_btn.setSizePolicy(sizePolicy)
        self.update_task_btn.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.update_task_btn.setFont(font)
        self.update_task_btn.setObjectName(_fromUtf8("update_task_btn"))
        self.horizontalLayout_9.addWidget(self.update_task_btn)
        self.delete_task_btn = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_task_btn.sizePolicy().hasHeightForWidth())
        self.delete_task_btn.setSizePolicy(sizePolicy)
        self.delete_task_btn.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.delete_task_btn.setFont(font)
        self.delete_task_btn.setObjectName(_fromUtf8("delete_task_btn"))
        self.horizontalLayout_9.addWidget(self.delete_task_btn)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_28.addLayout(self.verticalLayout_11)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 15, 1145, 713))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.frame_3 = QtGui.QFrame(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(160, 16777215))
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.layoutWidget1 = QtGui.QWidget(self.frame_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(5, 6, 153, 693))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_17 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_7.addWidget(self.label_17)
        self.member_name_line = QtGui.QLineEdit(self.layoutWidget1)
        self.member_name_line.setMinimumSize(QtCore.QSize(100, 25))
        self.member_name_line.setObjectName(_fromUtf8("member_name_line"))
        self.horizontalLayout_7.addWidget(self.member_name_line)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_18 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_17.addWidget(self.label_18)
        self.member_title_line = QtGui.QLineEdit(self.layoutWidget1)
        self.member_title_line.setMinimumSize(QtCore.QSize(100, 25))
        self.member_title_line.setObjectName(_fromUtf8("member_title_line"))
        self.horizontalLayout_17.addWidget(self.member_title_line)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.add_member_btn = QtGui.QPushButton(self.layoutWidget1)
        self.add_member_btn.setMinimumSize(QtCore.QSize(60, 0))
        self.add_member_btn.setMaximumSize(QtCore.QSize(1000, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_member_btn.setFont(font)
        self.add_member_btn.setIconSize(QtCore.QSize(30, 30))
        self.add_member_btn.setObjectName(_fromUtf8("add_member_btn"))
        self.horizontalLayout_18.addWidget(self.add_member_btn)
        self.delete_member_btn = QtGui.QPushButton(self.layoutWidget1)
        self.delete_member_btn.setMinimumSize(QtCore.QSize(60, 0))
        self.delete_member_btn.setMaximumSize(QtCore.QSize(1000, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_member_btn.setFont(font)
        self.delete_member_btn.setIconSize(QtCore.QSize(30, 30))
        self.delete_member_btn.setObjectName(_fromUtf8("delete_member_btn"))
        self.horizontalLayout_18.addWidget(self.delete_member_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.member_list = QtGui.QListWidget(self.layoutWidget1)
        self.member_list.setObjectName(_fromUtf8("member_list"))
        self.verticalLayout_3.addWidget(self.member_list)
        self.horizontalLayout_12.addWidget(self.frame_3)
        self.frame = QtGui.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.layoutWidget2 = QtGui.QWidget(self.frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 5, 969, 697))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_10 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_6.addWidget(self.label_10)
        self.task_tree = QtGui.QTreeWidget(self.layoutWidget2)
        self.task_tree.setObjectName(_fromUtf8("task_tree"))
        self.verticalLayout_6.addWidget(self.task_tree)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_11 = QtGui.QLabel(self.layoutWidget2)
        self.label_11.setMinimumSize(QtCore.QSize(350, 0))
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        self.assign_btn = QtGui.QPushButton(self.layoutWidget2)
        self.assign_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.assign_btn.setFont(font)
        self.assign_btn.setObjectName(_fromUtf8("assign_btn"))
        self.horizontalLayout_10.addWidget(self.assign_btn)
        self.unassign_btn = QtGui.QPushButton(self.layoutWidget2)
        self.unassign_btn.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.unassign_btn.setFont(font)
        self.unassign_btn.setObjectName(_fromUtf8("unassign_btn"))
        self.horizontalLayout_10.addWidget(self.unassign_btn)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setFrameShape(QtGui.QFrame.NoFrame)
        self.label.setFrameShadow(QtGui.QFrame.Raised)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setMargin(0)
        self.label.setIndent(3)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.assigned_task = QtGui.QListWidget(self.layoutWidget2)
        self.assigned_task.setObjectName(_fromUtf8("assigned_task"))
        self.verticalLayout_5.addWidget(self.assigned_task)
        self.horizontalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_12 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setIndent(3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_7.addWidget(self.label_12)
        self.task_desc = QtGui.QTextEdit(self.layoutWidget2)
        self.task_desc.setObjectName(_fromUtf8("task_desc"))
        self.verticalLayout_7.addWidget(self.task_desc)
        self.horizontalLayout_11.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12.addWidget(self.frame)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.layoutWidget3 = QtGui.QWidget(self.tab2)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 1145, 717))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_2 = QtGui.QLabel(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.query_member = QtGui.QComboBox(self.layoutWidget3)
        self.query_member.setMinimumSize(QtCore.QSize(0, 20))
        self.query_member.setMaximumSize(QtCore.QSize(16777215, 25))
        self.query_member.setObjectName(_fromUtf8("query_member"))
        self.query_member.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.query_member)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(20, 20))
        self.label_5.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.query_fromdate = QtGui.QDateEdit(self.layoutWidget3)
        self.query_fromdate.setMinimumSize(QtCore.QSize(100, 20))
        self.query_fromdate.setMaximumSize(QtCore.QSize(100, 20))
        self.query_fromdate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.query_fromdate.setObjectName(_fromUtf8("query_fromdate"))
        self.horizontalLayout_4.addWidget(self.query_fromdate)
        self.label_6 = QtGui.QLabel(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(20, 20))
        self.label_6.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setMidLineWidth(0)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.query_todate = QtGui.QDateEdit(self.layoutWidget3)
        self.query_todate.setMinimumSize(QtCore.QSize(0, 20))
        self.query_todate.setMaximumSize(QtCore.QSize(100, 20))
        self.query_todate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.query_todate.setObjectName(_fromUtf8("query_todate"))
        self.horizontalLayout_4.addWidget(self.query_todate)
        self.label_14 = QtGui.QLabel(self.layoutWidget3)
        self.label_14.setMinimumSize(QtCore.QSize(400, 0))
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_4.addWidget(self.label_14)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_4)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(80, 0))
        self.label_7.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.query_project = QtGui.QComboBox(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.query_project.sizePolicy().hasHeightForWidth())
        self.query_project.setSizePolicy(sizePolicy)
        self.query_project.setMinimumSize(QtCore.QSize(0, 20))
        self.query_project.setMaximumSize(QtCore.QSize(16777215, 25))
        self.query_project.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.query_project.setObjectName(_fromUtf8("query_project"))
        self.query_project.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.query_project)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_5)
        self.label_15 = QtGui.QLabel(self.layoutWidget3)
        self.label_15.setMinimumSize(QtCore.QSize(30, 0))
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_15.addWidget(self.label_15)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_13 = QtGui.QLabel(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(80, 0))
        self.label_13.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_13.addWidget(self.label_13)
        self.query_subproject = QtGui.QComboBox(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.query_subproject.sizePolicy().hasHeightForWidth())
        self.query_subproject.setSizePolicy(sizePolicy)
        self.query_subproject.setMinimumSize(QtCore.QSize(0, 20))
        self.query_subproject.setMaximumSize(QtCore.QSize(16777215, 25))
        self.query_subproject.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.query_subproject.setObjectName(_fromUtf8("query_subproject"))
        self.query_subproject.addItem(_fromUtf8(""))
        self.horizontalLayout_13.addWidget(self.query_subproject)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_13)
        self.query = QtGui.QPushButton(self.layoutWidget3)
        self.query.setMinimumSize(QtCore.QSize(100, 25))
        self.query.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.query.setFont(font)
        self.query.setObjectName(_fromUtf8("query"))
        self.horizontalLayout_15.addWidget(self.query)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.query_overtime_table = QtGui.QTableWidget(self.layoutWidget3)
        self.query_overtime_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.query_overtime_table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.query_overtime_table.setObjectName(_fromUtf8("query_overtime_table"))
        self.query_overtime_table.setColumnCount(0)
        self.query_overtime_table.setRowCount(0)
        self.query_overtime_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_10.addWidget(self.query_overtime_table)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_16 = QtGui.QLabel(self.layoutWidget3)
        self.label_16.setMinimumSize(QtCore.QSize(900, 0))
        self.label_16.setText(_fromUtf8(""))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_16.addWidget(self.label_16)
        self.save_excel = QtGui.QPushButton(self.layoutWidget3)
        self.save_excel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.save_excel.setFont(font)
        self.save_excel.setObjectName(_fromUtf8("save_excel"))
        self.horizontalLayout_16.addWidget(self.save_excel)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.layoutWidget4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 10, 266, 61))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.dep_line = QtGui.QComboBox(self.layoutWidget4)
        self.dep_line.setEnabled(False)
        self.dep_line.setMinimumSize(QtCore.QSize(200, 30))
        self.dep_line.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dep_line.setEditable(False)
        self.dep_line.setObjectName(_fromUtf8("dep_line"))
        self.dep_line.addItem(_fromUtf8(""))
        self.dep_line.addItem(_fromUtf8(""))
        self.dep_line.addItem(_fromUtf8(""))
        self.dep_line.addItem(_fromUtf8(""))
        self.dep_line.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.dep_line)
        self.dep_edit = QtGui.QPushButton(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dep_edit.sizePolicy().hasHeightForWidth())
        self.dep_edit.setSizePolicy(sizePolicy)
        self.dep_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.dep_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(9)
        self.dep_edit.setFont(font)
        self.dep_edit.setObjectName(_fromUtf8("dep_edit"))
        self.horizontalLayout.addWidget(self.dep_edit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.label_3.setText(_translate("MainWindow", "项目列表", None))
        item = self.project_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "项目名称", None))
        item = self.project_list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "总进度", None))
        self.label_21.setText(_translate("MainWindow", "项目名称", None))
        self.label_22.setText(_translate("MainWindow", "起始时间", None))
        self.label_23.setText(_translate("MainWindow", "结束时间", None))
        self.label_24.setText(_translate("MainWindow", "项目描述", None))
        self.add_project_btn.setText(_translate("MainWindow", "添加项目", None))
        self.delete_project_btn.setText(_translate("MainWindow", "删除项目", None))
        self.label_4.setText(_translate("MainWindow", "子项目列表", None))
        item = self.subproject_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "子项目名称", None))
        item = self.subproject_list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "项目进度", None))
        self.label_25.setText(_translate("MainWindow", "子项目名称", None))
        self.label_29.setText(_translate("MainWindow", "项目类型", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "游戏", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "动画", None))
        self.label_26.setText(_translate("MainWindow", "起始时间", None))
        self.label_27.setText(_translate("MainWindow", "结束时间", None))
        self.label_28.setText(_translate("MainWindow", "子项目描述", None))
        self.add_subproject_btn.setText(_translate("MainWindow", "添加子项目", None))
        self.delete_subproject_btn.setText(_translate("MainWindow", "删除子项目", None))
        self.label_8.setText(_translate("MainWindow", "任务列表", None))
        item = self.task_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "任务名称", None))
        item = self.task_list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "任务进度", None))
        self.label_19.setText(_translate("MainWindow", "任务名称", None))
        self.label_30.setText(_translate("MainWindow", "起始时间", None))
        self.label_31.setText(_translate("MainWindow", "结束时间", None))
        self.label_20.setText(_translate("MainWindow", "任务描述", None))
        self.add_task_btn.setText(_translate("MainWindow", "添加任务", None))
        self.update_task_btn.setText(_translate("MainWindow", "更新任务", None))
        self.delete_task_btn.setText(_translate("MainWindow", "删除任务", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "项目管理", None))
        self.label_9.setText(_translate("MainWindow", "成员列表", None))
        self.label_17.setText(_translate("MainWindow", "姓名", None))
        self.label_18.setText(_translate("MainWindow", "职务", None))
        self.add_member_btn.setText(_translate("MainWindow", "添加成员", None))
        self.delete_member_btn.setText(_translate("MainWindow", "删除成员", None))
        self.label_10.setText(_translate("MainWindow", "待定", None))
        self.assign_btn.setText(_translate("MainWindow", "分配任务", None))
        self.unassign_btn.setText(_translate("MainWindow", "取消分配", None))
        self.label.setText(_translate("MainWindow", "已分配任务", None))
        self.label_12.setText(_translate("MainWindow", "任务描述", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "成员管理", None))
        self.label_2.setText(_translate("MainWindow", "查询成员", None))
        self.query_member.setItemText(0, _translate("MainWindow", "*", None))
        self.label_5.setText(_translate("MainWindow", "从", None))
        self.query_fromdate.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.label_6.setText(_translate("MainWindow", "至", None))
        self.query_todate.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.label_7.setText(_translate("MainWindow", "查询项目", None))
        self.query_project.setItemText(0, _translate("MainWindow", "*", None))
        self.label_13.setText(_translate("MainWindow", "查询展项", None))
        self.query_subproject.setItemText(0, _translate("MainWindow", "*", None))
        self.query.setText(_translate("MainWindow", "开始查询", None))
        self.query_overtime_table.setSortingEnabled(True)
        self.save_excel.setText(_translate("MainWindow", "保存到Excel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MainWindow", "加班统计", None))
        self.dep_line.setItemText(0, _translate("MainWindow", "三维动画", None))
        self.dep_line.setItemText(1, _translate("MainWindow", "投标动画", None))
        self.dep_line.setItemText(2, _translate("MainWindow", "二维动画", None))
        self.dep_line.setItemText(3, _translate("MainWindow", "平面设计", None))
        self.dep_line.setItemText(4, _translate("MainWindow", "编导", None))
        self.dep_edit.setText(_translate("MainWindow", "更改", None))

