# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dev\overtime-management\ui_memberClient.ui'
#
# Created: Wed Oct 25 23:27:57 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from newTable import * 

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(QtGui.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1200, 800)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 800))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle(_fromUtf8(""))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 1181, 726))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.layoutWidget = QtGui.QWidget(self.tab1)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 25, 1151, 671))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabWidget_2 = QtGui.QTabWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_2 = QtGui.QWidget()
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tab_2.setFont(font)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(5, 10, 1066, 32))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_32 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout.addWidget(self.label_32)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(200, 0))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.label_tables = QtGui.QLabel(self.layoutWidget1)
        self.label_tables.setObjectName(_fromUtf8("label_tables"))
        self.horizontalLayout.addWidget(self.label_tables)
        self.layoutWidget2 = QtGui.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(5, 50, 1131, 601))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_20.setMargin(0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tree_project = QtGui.QTreeWidget(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_project.sizePolicy().hasHeightForWidth())
        self.tree_project.setSizePolicy(sizePolicy)
        self.tree_project.setMaximumSize(QtCore.QSize(250, 16777215))
        self.tree_project.setObjectName(_fromUtf8("tree_project"))
        self.tree_project.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout.addWidget(self.tree_project)
        self.horizontalLayout_20.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.table_prodetail = NewTable(self.layoutWidget2)
        self.table_prodetail.setObjectName(_fromUtf8("table_prodetail"))
        self.table_prodetail.setColumnCount(0)
        self.table_prodetail.setRowCount(0)
        self.table_prodetail.horizontalHeader().setStretchLastSection(True)
        self.table_prodetail.verticalHeader().setVisible(False)
        self.table_prodetail.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.verticalLayout_2.addWidget(self.table_prodetail)
        self.horizontalLayout_20.addLayout(self.verticalLayout_2)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(5, 10, 1136, 631))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        label1 = QtGui.QLabel(u'只显示项目')
        label1.setSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        label2 = QtGui.QLabel(u'只显示展项')
        label2.setSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        label3 = QtGui.QLabel(u'只显示人员')
        label3.setSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        space = QtGui.QLabel('')
        space.setMaximumWidth(30)
        self.combo_scheduleProjectFilter = QtGui.QComboBox(self.layoutWidget_2)
        self.combo_scheduleProjectFilter.setMinimumWidth(200)
        self.combo_scheduleProjectFilter.setObjectName(_fromUtf8("combo_scheduleProjectFilter"))
        self.combo_scheduleSubprojectFilter = QtGui.QComboBox(self.layoutWidget_2)
        self.combo_scheduleSubprojectFilter.setMinimumWidth(200)
        self.combo_scheduleSubprojectFilter.setObjectName(_fromUtf8("combo_scheduleSubprojectFilter"))
        self.combo_scheduleMemberFilter = QtGui.QComboBox(self.layoutWidget_2)
        self.combo_scheduleMemberFilter.setMinimumWidth(80)
        self.combo_scheduleMemberFilter.setObjectName(_fromUtf8("combo_scheduleMemberFilter"))
        self.check_scheduleShowDetail = QtGui.QCheckBox(u'显示详情信息')
        self.horizontalLayout_9.addWidget(label1)
        self.horizontalLayout_9.addWidget(self.combo_scheduleProjectFilter)
        self.horizontalLayout_9.addWidget(space)
        self.horizontalLayout_9.addWidget(label2)
        self.horizontalLayout_9.addWidget(self.combo_scheduleSubprojectFilter)
        self.horizontalLayout_9.addWidget(space)
        self.horizontalLayout_9.addWidget(label3)
        self.horizontalLayout_9.addWidget(self.combo_scheduleMemberFilter)        
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)

        self.horizontalLayout_9.addWidget(self.check_scheduleShowDetail)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.label_19 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_9.addWidget(self.label_19)
        self.period_combo = QtGui.QComboBox(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.period_combo.sizePolicy().hasHeightForWidth())
        self.period_combo.setSizePolicy(sizePolicy)
        self.period_combo.setMinimumSize(QtCore.QSize(100, 0))
        self.period_combo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.period_combo.setModelColumn(0)
        self.period_combo.setObjectName(_fromUtf8("period_combo"))
        self.period_combo.addItem(_fromUtf8(""))
        self.period_combo.addItem(_fromUtf8(""))
        self.period_combo.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.period_combo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(1)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.entry_list = QtGui.QTreeWidget(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_list.sizePolicy().hasHeightForWidth())
        self.entry_list.setSizePolicy(sizePolicy)
        self.entry_list.setMaximumSize(QtCore.QSize(250, 16777215))
        self.entry_list.setSizeIncrement(QtCore.QSize(0, 0))
        self.entry_list.setBaseSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.entry_list.setFont(font)
        self.entry_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.entry_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.entry_list.setAlternatingRowColors(True)
        self.entry_list.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.entry_list.setIndentation(20)
        self.entry_list.setRootIsDecorated(True)
        self.entry_list.setUniformRowHeights(False)
        self.entry_list.setAllColumnsShowFocus(False)
        self.entry_list.setHeaderHidden(False)
        self.entry_list.setObjectName(_fromUtf8("entry_list"))
        item_0 = QtGui.QTreeWidgetItem(self.entry_list)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.horizontalLayout_21.addWidget(self.entry_list)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.period1_table = NewTable(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.period1_table.sizePolicy().hasHeightForWidth())
        self.period1_table.setSizePolicy(sizePolicy)
        self.period1_table.setMinimumSize(QtCore.QSize(0, 15))
        self.period1_table.setMaximumSize(QtCore.QSize(16777215, 25))
        self.period1_table.setBaseSize(QtCore.QSize(0, 0))
        self.period1_table.setFrameShape(QtGui.QFrame.StyledPanel)
        self.period1_table.setLineWidth(1)
        self.period1_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.period1_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.period1_table.setAutoScrollMargin(16)
        self.period1_table.setWordWrap(True)
        self.period1_table.setCornerButtonEnabled(False)
        self.period1_table.setColumnCount(14)
        self.period1_table.setObjectName(_fromUtf8("period1_table"))
        self.period1_table.setRowCount(0)
        self.period1_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.verticalLayout_11.addWidget(self.period1_table)
        self.period2_table = NewTable(self.layoutWidget_2)
        self.period2_table.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.period2_table.sizePolicy().hasHeightForWidth())
        self.period2_table.setSizePolicy(sizePolicy)
        self.period2_table.setMinimumSize(QtCore.QSize(0, 15))
        self.period2_table.setMaximumSize(QtCore.QSize(16777215, 25))
        self.period2_table.setBaseSize(QtCore.QSize(0, 0))
        self.period2_table.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.period2_table.setLineWidth(1)
        self.period2_table.setMidLineWidth(0)
        self.period2_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.period2_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.period2_table.setAutoScrollMargin(1)
        self.period2_table.setColumnCount(10)
        self.period2_table.setObjectName(_fromUtf8("period2_table"))
        self.period2_table.setRowCount(0)
        self.period2_table.horizontalHeader().setHighlightSections(False)
        self.period2_table.verticalHeader().setVisible(False)
        self.period2_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.verticalLayout_11.addWidget(self.period2_table)
        self.schedule_table = NewTable(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_table.sizePolicy().hasHeightForWidth())
        self.schedule_table.setSizePolicy(sizePolicy)
        self.schedule_table.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.schedule_table.setFont(font)
        self.schedule_table.setFrameShadow(QtGui.QFrame.Sunken)
        self.schedule_table.setAutoScroll(False)
        self.schedule_table.setAutoScrollMargin(16)
        self.schedule_table.setAlternatingRowColors(False)
        self.schedule_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.schedule_table.setShowGrid(True)
        self.schedule_table.setGridStyle(QtCore.Qt.DashLine)
        self.schedule_table.setRowCount(10)
        self.schedule_table.setColumnCount(10)
        self.schedule_table.setObjectName(_fromUtf8("schedule_table"))
        self.schedule_table.horizontalHeader().setVisible(False)
        self.schedule_table.horizontalHeader().setHighlightSections(False)
        self.schedule_table.verticalHeader().setVisible(False)
        self.schedule_table.verticalHeader().setStretchLastSection(False)
        self.schedule_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.verticalLayout_11.addWidget(self.schedule_table)
        self.horizontalLayout_21.addLayout(self.verticalLayout_11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tab_4)
        self.tabWidget_3.setGeometry(QtCore.QRect(5, 10, 1166, 686))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget_3.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.layoutWidget3 = QtGui.QWidget(self.tab_5)
        self.layoutWidget3.setGeometry(QtCore.QRect(5, 10, 1146, 646))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.frame = QtGui.QFrame(self.layoutWidget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(300, 0))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_18 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(90, 30))
        self.label_18.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_22.addWidget(self.label_18)
        self.apply_date = QtGui.QDateEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_date.sizePolicy().hasHeightForWidth())
        self.apply_date.setSizePolicy(sizePolicy)
        self.apply_date.setMinimumSize(QtCore.QSize(0, 25))
        self.apply_date.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.apply_date.setFont(font)
        self.apply_date.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.apply_date.setCalendarPopup(True)
        self.apply_date.setObjectName(_fromUtf8("apply_date"))
        self.horizontalLayout_22.addWidget(self.apply_date)
        self.verticalLayout_6.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_29 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(90, 30))
        self.label_29.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_23.addWidget(self.label_29)
        self.apply_project = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_project.sizePolicy().hasHeightForWidth())
        self.apply_project.setSizePolicy(sizePolicy)
        self.apply_project.setMinimumSize(QtCore.QSize(0, 25))
        self.apply_project.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.apply_project.setFont(font)
        self.apply_project.setEditable(False)
        self.apply_project.setObjectName(_fromUtf8("apply_project"))
        self.apply_project.addItem(_fromUtf8(""))
        self.horizontalLayout_23.addWidget(self.apply_project)
        self.verticalLayout_6.addLayout(self.horizontalLayout_23)        
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_27 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(90, 0))
        self.label_27.setMaximumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_24.addWidget(self.label_27)
        self.apply_subproject = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_subproject.sizePolicy().hasHeightForWidth())
        self.apply_subproject.setSizePolicy(sizePolicy)
        self.apply_subproject.setMinimumSize(QtCore.QSize(0, 25))
        self.apply_subproject.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.apply_subproject.setFont(font)
        self.apply_subproject.setFrame(True)
        self.apply_subproject.setObjectName(_fromUtf8("apply_subproject"))
        self.apply_subproject.addItem(_fromUtf8(""))
        self.horizontalLayout_24.addWidget(self.apply_subproject)
        self.verticalLayout_6.addLayout(self.horizontalLayout_24)

        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_20 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_27.addWidget(self.label_20)
        self.apply_duration = QtGui.QDoubleSpinBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_duration.sizePolicy().hasHeightForWidth())
        self.apply_duration.setSizePolicy(sizePolicy)
        self.apply_duration.setMinimumSize(QtCore.QSize(0, 25))
        self.apply_duration.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.apply_duration.setFont(font)
        self.apply_duration.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.apply_duration.setDecimals(1)
        self.apply_duration.setSingleStep(0.5)
        self.apply_duration.setProperty("value", 0.0)
        self.apply_duration.setObjectName(_fromUtf8("apply_duration"))
        self.horizontalLayout_27.addWidget(self.apply_duration)
        self.verticalLayout_6.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_25 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(90, 30))
        self.label_25.setMaximumSize(QtCore.QSize(50, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_28.addWidget(self.label_25)
        self.apply_meal = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_meal.sizePolicy().hasHeightForWidth())
        self.apply_meal.setSizePolicy(sizePolicy)
        self.apply_meal.setMinimumSize(QtCore.QSize(0, 25))
        self.apply_meal.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.apply_meal.setFont(font)
        self.apply_meal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.apply_meal.setObjectName(_fromUtf8("apply_meal"))
        self.horizontalLayout_28.addWidget(self.apply_meal)
        self.verticalLayout_6.addLayout(self.horizontalLayout_28)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_30 = QtGui.QLabel(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(80, 30))
        self.label_30.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_12.addWidget(self.label_30)
        self.desc = QtGui.QTextEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desc.sizePolicy().hasHeightForWidth())
        self.desc.setSizePolicy(sizePolicy)
        self.desc.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.desc.setFont(font)
        self.desc.setObjectName(_fromUtf8("desc"))
        self.verticalLayout_12.addWidget(self.desc)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setSpacing(6)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.apply_overtime = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_overtime.sizePolicy().hasHeightForWidth())
        self.apply_overtime.setSizePolicy(sizePolicy)
        self.apply_overtime.setMinimumSize(QtCore.QSize(20, 30))
        self.apply_overtime.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.apply_overtime.setFont(font)
        self.apply_overtime.setObjectName(_fromUtf8("apply_overtime"))
        self.horizontalLayout_26.addWidget(self.apply_overtime)
        self.verticalLayout_12.addLayout(self.horizontalLayout_26)
        self.verticalLayout_6.addLayout(self.verticalLayout_12)
        self.horizontalLayout_3.addWidget(self.frame)
        self.frame_12 = QtGui.QFrame(self.layoutWidget3)
        self.frame_12.setFrameShape(QtGui.QFrame.Box)
        self.frame_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_12.setObjectName(_fromUtf8("frame_12"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.frame_12)
        self.verticalLayout_25.setSpacing(6)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.horizontalLayout_55 = QtGui.QHBoxLayout()
        self.horizontalLayout_55.setObjectName(_fromUtf8("horizontalLayout_55"))
        self.horizontalLayout_56 = QtGui.QHBoxLayout()
        self.horizontalLayout_56.setObjectName(_fromUtf8("horizontalLayout_56"))
        self.label_61 = QtGui.QLabel(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_61.sizePolicy().hasHeightForWidth())
        self.label_61.setSizePolicy(sizePolicy)
        self.label_61.setMinimumSize(QtCore.QSize(80, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_61.setFont(font)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.horizontalLayout_56.addWidget(self.label_61)
        #self.query_member = QtGui.QComboBox(self.frame_12)
        #sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        #sizePolicy.setHorizontalStretch(0)
        #sizePolicy.setVerticalStretch(0)
        #sizePolicy.setHeightForWidth(self.member.ember.sizePolicy().hasHeightForWidth())
        #self.query_member.setSizePolicy(sizePolicy)
        #self.query_member.setMinimumSize(QtCore.QSize(0, 25))
        #self.query_member.setMaximumSize(QtCore.QSize(16777215, 25))
        #font = QtGui.QFont()
        #font.setPointSize(10)
        #self.query_member.setFont(font)
        #self.query_member.setObjectName(_fromUtf8("query_member"))
        #self.query_member.addItem(_fromUtf8(""))
        #self.horizontalLayout_56.addWidget(self.query_member)
        self.horizontalLayout_55.addLayout(self.horizontalLayout_56)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_62 = QtGui.QLabel(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_62.sizePolicy().hasHeightForWidth())
        self.label_62.setSizePolicy(sizePolicy)
        self.label_62.setMinimumSize(QtCore.QSize(20, 25))
        self.label_62.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.label_62.setFont(font)
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.horizontalLayout_4.addWidget(self.label_62)
        self.query_fromdate = QtGui.QDateEdit(self.frame_12)
        self.query_fromdate.setMinimumSize(QtCore.QSize(100, 25))
        self.query_fromdate.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.query_fromdate.setFont(font)
        self.query_fromdate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.query_fromdate.setCurrentSection(QtGui.QDateTimeEdit.YearSection)
        self.query_fromdate.setCalendarPopup(True)
        self.query_fromdate.setObjectName(_fromUtf8("query_fromdate"))
        self.horizontalLayout_4.addWidget(self.query_fromdate)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_63 = QtGui.QLabel(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_63.sizePolicy().hasHeightForWidth())
        self.label_63.setSizePolicy(sizePolicy)
        self.label_63.setMinimumSize(QtCore.QSize(20, 25))
        self.label_63.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.label_63.setFont(font)
        self.label_63.setMidLineWidth(0)
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.horizontalLayout_5.addWidget(self.label_63)
        self.query_todate = QtGui.QDateEdit(self.frame_12)
        self.query_todate.setMinimumSize(QtCore.QSize(0, 25))
        self.query_todate.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.query_todate.setFont(font)
        self.query_todate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.query_todate.setCurrentSection(QtGui.QDateTimeEdit.YearSection)
        self.query_todate.setCalendarPopup(True)
        self.query_todate.setObjectName(_fromUtf8("query_todate"))
        self.horizontalLayout_5.addWidget(self.query_todate)
        self.query = QtGui.QPushButton(self.frame_12)
        self.query.setMinimumSize(QtCore.QSize(150, 25))
        self.query.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.query.setFont(font)
        self.query.setObjectName(_fromUtf8("query"))
        self.horizontalLayout_5.addWidget(self.query)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_55.addLayout(self.horizontalLayout_7)
        self.verticalLayout_26.addLayout(self.horizontalLayout_55)
        self.horizontalLayout_58 = QtGui.QHBoxLayout()
        self.horizontalLayout_58.setObjectName(_fromUtf8("horizontalLayout_58"))
        self.horizontalLayout_59 = QtGui.QHBoxLayout()
        self.horizontalLayout_59.setObjectName(_fromUtf8("horizontalLayout_59"))
        self.label_65 = QtGui.QLabel(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_65.sizePolicy().hasHeightForWidth())
        self.label_65.setSizePolicy(sizePolicy)
        self.label_65.setMinimumSize(QtCore.QSize(80, 25))
        self.label_65.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_65.setFont(font)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.horizontalLayout_59.addWidget(self.label_65)
        self.query_project = QtGui.QComboBox(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.query_project.sizePolicy().hasHeightForWidth())
        self.query_project.setSizePolicy(sizePolicy)
        self.query_project.setMinimumSize(QtCore.QSize(0, 20))
        self.query_project.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.query_project.setFont(font)
        self.query_project.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.query_project.setObjectName(_fromUtf8("query_project"))
        self.query_project.addItem(_fromUtf8(""))
        self.horizontalLayout_59.addWidget(self.query_project)
        self.horizontalLayout_58.addLayout(self.horizontalLayout_59)
        self.label_66 = QtGui.QLabel(self.frame_12)
        self.label_66.setMinimumSize(QtCore.QSize(10, 0))
        self.label_66.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_66.setText(_fromUtf8(""))
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.horizontalLayout_58.addWidget(self.label_66)
        self.horizontalLayout_60 = QtGui.QHBoxLayout()
        self.horizontalLayout_60.setObjectName(_fromUtf8("horizontalLayout_60"))
        self.label_67 = QtGui.QLabel(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_67.sizePolicy().hasHeightForWidth())
        self.label_67.setSizePolicy(sizePolicy)
        self.label_67.setMinimumSize(QtCore.QSize(80, 25))
        self.label_67.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_67.setFont(font)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.horizontalLayout_60.addWidget(self.label_67)
        self.query_subproject = QtGui.QComboBox(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.query_subproject.sizePolicy().hasHeightForWidth())
        self.query_subproject.setSizePolicy(sizePolicy)
        self.query_subproject.setMinimumSize(QtCore.QSize(0, 25))
        self.query_subproject.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.query_subproject.setFont(font)
        self.query_subproject.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.query_subproject.setObjectName(_fromUtf8("query_subproject"))
        self.query_subproject.addItem(_fromUtf8(""))
        self.horizontalLayout_60.addWidget(self.query_subproject)
        self.horizontalLayout_58.addLayout(self.horizontalLayout_60)
        self.verticalLayout_26.addLayout(self.horizontalLayout_58)
        self.verticalLayout_25.addLayout(self.verticalLayout_26)
        self.query_overtime_table = NewTable(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.query_overtime_table.sizePolicy().hasHeightForWidth())
        self.query_overtime_table.setSizePolicy(sizePolicy)
        self.query_overtime_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.query_overtime_table.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.query_overtime_table.setObjectName(_fromUtf8("query_overtime_table"))
        self.query_overtime_table.setColumnCount(0)
        self.query_overtime_table.setRowCount(0)
        self.query_overtime_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_25.addWidget(self.query_overtime_table)
        self.horizontalLayout_61 = QtGui.QHBoxLayout()
        self.horizontalLayout_61.setObjectName(_fromUtf8("horizontalLayout_61"))
        self.label_68 = QtGui.QLabel(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_68.sizePolicy().hasHeightForWidth())
        self.label_68.setSizePolicy(sizePolicy)
        self.label_68.setMinimumSize(QtCore.QSize(400, 0))
        self.label_68.setText(_fromUtf8(""))
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_61.addWidget(self.label_68)
        self.save_excel = QtGui.QPushButton(self.frame_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_excel.sizePolicy().hasHeightForWidth())
        self.save_excel.setSizePolicy(sizePolicy)
        self.save_excel.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_excel.setFont(font)
        self.save_excel.setObjectName(_fromUtf8("save_excel"))
        self.horizontalLayout_61.addWidget(self.save_excel)
        self.verticalLayout_25.addLayout(self.horizontalLayout_61)
        self.horizontalLayout_3.addWidget(self.frame_12)
        self.tabWidget_3.addTab(self.tab_5, _fromUtf8(""))
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.line_welcom = QtGui.QLabel(self.centralwidget)
        self.line_welcom.setGeometry(QtCore.QRect(10, 15, 176, 26))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line_welcom.setFont(font)
        self.line_welcom.setObjectName(_fromUtf8("line_welcom"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.label_32.setText(_translate("MainWindow", "项目列表", None))
        self.label_tables.setText(_translate("MainWindow", "项目详情", None))
        self.table_prodetail.setSortingEnabled(True)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "详细信息", None))
        self.check_scheduleShowDetail.setText(_translate("MainWindow", "显示详情", None))
        self.label_19.setText(_translate("MainWindow", "显示周期", None))
        self.period_combo.setItemText(0, _translate("MainWindow", "月", None))
        self.period_combo.setItemText(1, _translate("MainWindow", "周", None))
        self.period_combo.setItemText(2, _translate("MainWindow", "日", None))
        self.entry_list.headerItem().setText(0, _translate("MainWindow", "项目列表", None))
        __sortingEnabled = self.entry_list.isSortingEnabled()
        self.entry_list.setSortingEnabled(False)
        self.entry_list.topLevelItem(0).setText(0, _translate("MainWindow", "项目1", None))
        self.entry_list.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "展项1", None))
        self.entry_list.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "任务1", None))
        self.entry_list.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "展项2", None))
        self.entry_list.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "任务2", None))
        self.entry_list.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "任务进度", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "项目管理", None))
        self.label_18.setText(_translate("MainWindow", "加班日期", None))
        self.apply_date.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.label_27.setText(_translate("MainWindow", "加班子项目", None))
        self.apply_subproject.setItemText(0, _translate("MainWindow", "*", None))
        self.label_29.setText(_translate("MainWindow", "加班项目", None))
        self.apply_project.setItemText(0, _translate("MainWindow", "*", None))
        self.label_20.setText(_translate("MainWindow", "加班时长", None))
        self.label_25.setText(_translate("MainWindow", "加班餐", None))
        self.label_30.setText(_translate("MainWindow", "加班描述", None))
        self.desc.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>", None))
        self.apply_overtime.setText(_translate("MainWindow", "申请加班", None))
        self.label_61.setText(_translate("MainWindow", "查询日期", None))
        #self.query_member.setItemText(0, _translate("MainWindow", "*", None))
        self.label_62.setText(_translate("MainWindow", "从", None))
        self.query_fromdate.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.label_63.setText(_translate("MainWindow", "至", None))
        self.query_todate.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.query.setText(_translate("MainWindow", "加班查询", None))
        self.label_65.setText(_translate("MainWindow", "查询项目", None))
        self.query_project.setItemText(0, _translate("MainWindow", "*", None))
        self.label_67.setText(_translate("MainWindow", "查询展项", None))
        self.query_subproject.setItemText(0, _translate("MainWindow", "*", None))
        self.query_overtime_table.setSortingEnabled(True)
        self.save_excel.setText(_translate("MainWindow", "保存到Excel", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "加班", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "日常/加班", None))
        self.line_welcom.setText(_translate("MainWindow", "你好，姚灏", None))

