# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dev\overtime-management\ui_mainwindow.ui'
#
# Created: Fri Sep 15 21:52:29 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MemberMainWindow(QtGui.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(620, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(620, 600))
        MainWindow.setMaximumSize(QtCore.QSize(620, 600))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(15, 10, 591, 536))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.name = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.name.setFont(font)
        self.name.setObjectName(_fromUtf8("name"))
        self.horizontalLayout.addWidget(self.name)
        self.name_line = QtGui.QLineEdit(self.widget)
        self.name_line.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.name_line.setFont(font)
        self.name_line.setObjectName(_fromUtf8("name_line"))
        self.horizontalLayout.addWidget(self.name_line)
        self.name_edit = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_edit.sizePolicy().hasHeightForWidth())
        self.name_edit.setSizePolicy(sizePolicy)
        self.name_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(9)
        self.name_edit.setFont(font)
        self.name_edit.setObjectName(_fromUtf8("name_edit"))
        self.horizontalLayout.addWidget(self.name_edit)
        self.dep = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        self.dep.setFont(font)
        self.dep.setObjectName(_fromUtf8("dep"))
        self.horizontalLayout.addWidget(self.dep)
        self.dep_line = QtGui.QComboBox(self.widget)
        self.dep_line.setEnabled(False)
        self.dep_line.setMinimumSize(QtCore.QSize(200, 0))
        self.dep_line.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dep_line.setEditable(False)
        self.dep_line.setObjectName(_fromUtf8("dep_line"))
        self.dep_line.addItem(_fromUtf8(""))
        self.dep_line.addItem(_fromUtf8(""))
        self.dep_line.addItem(_fromUtf8(""))
        self.dep_line.addItem(_fromUtf8(""))
        self.dep_line.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.dep_line)
        self.dep_edit = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dep_edit.sizePolicy().hasHeightForWidth())
        self.dep_edit.setSizePolicy(sizePolicy)
        self.dep_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Adobe Arabic"))
        font.setPointSize(9)
        self.dep_edit.setFont(font)
        self.dep_edit.setObjectName(_fromUtf8("dep_edit"))
        self.horizontalLayout.addWidget(self.dep_edit)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_3.addWidget(self.label_10)
        self.tabWidget = QtGui.QTabWidget(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.widget1 = QtGui.QWidget(self.tab_2)
        self.widget1.setGeometry(QtCore.QRect(15, 22, 556, 401))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.widget1)
        self.label.setMinimumSize(QtCore.QSize(80, 30))
        self.label.setMaximumSize(QtCore.QSize(80, 30))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.apply_date = QtGui.QDateEdit(self.widget1)
        self.apply_date.setMaximumSize(QtCore.QSize(16777215, 30))
        self.apply_date.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.apply_date.setObjectName(_fromUtf8("apply_date"))
        self.horizontalLayout_2.addWidget(self.apply_date)
        self.label_3 = QtGui.QLabel(self.widget1)
        self.label_3.setMinimumSize(QtCore.QSize(70, 30))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.apply_duration = QtGui.QSpinBox(self.widget1)
        self.apply_duration.setMinimumSize(QtCore.QSize(0, 30))
        self.apply_duration.setMaximumSize(QtCore.QSize(16777215, 30))
        self.apply_duration.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.apply_duration.setObjectName(_fromUtf8("apply_duration"))
        self.horizontalLayout_2.addWidget(self.apply_duration)
        self.label_4 = QtGui.QLabel(self.widget1)
        self.label_4.setMinimumSize(QtCore.QSize(50, 30))
        self.label_4.setMaximumSize(QtCore.QSize(50, 30))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.apply_meal = QtGui.QLineEdit(self.widget1)
        self.apply_meal.setMinimumSize(QtCore.QSize(0, 30))
        self.apply_meal.setMaximumSize(QtCore.QSize(16777215, 30))
        self.apply_meal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.apply_meal.setObjectName(_fromUtf8("apply_meal"))
        self.horizontalLayout_2.addWidget(self.apply_meal)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.widget1)
        self.label_2.setMinimumSize(QtCore.QSize(90, 30))
        self.label_2.setMaximumSize(QtCore.QSize(80, 30))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.apply_project = QtGui.QComboBox(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_project.sizePolicy().hasHeightForWidth())
        self.apply_project.setSizePolicy(sizePolicy)
        self.apply_project.setMinimumSize(QtCore.QSize(0, 30))
        self.apply_project.setMaximumSize(QtCore.QSize(16777215, 30))
        self.apply_project.setEditable(False)
        self.apply_project.setObjectName(_fromUtf8("apply_project"))
        self.apply_project.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.apply_project)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_8 = QtGui.QLabel(self.widget1)
        self.label_8.setMaximumSize(QtCore.QSize(90, 30))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_6.addWidget(self.label_8)
        self.apply_subproject = QtGui.QComboBox(self.widget1)
        self.apply_subproject.setMinimumSize(QtCore.QSize(0, 30))
        self.apply_subproject.setObjectName(_fromUtf8("apply_subproject"))
        self.apply_subproject.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.apply_subproject)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_9 = QtGui.QLabel(self.widget1)
        self.label_9.setMinimumSize(QtCore.QSize(80, 30))
        self.label_9.setMaximumSize(QtCore.QSize(80, 30))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.desc = QtGui.QTextEdit(self.widget1)
        self.desc.setObjectName(_fromUtf8("desc"))
        self.verticalLayout.addWidget(self.desc)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_11 = QtGui.QLabel(self.widget1)
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_7.addWidget(self.label_11)
        self.apply_overtime = QtGui.QPushButton(self.widget1)
        self.apply_overtime.setMinimumSize(QtCore.QSize(100, 40))
        self.apply_overtime.setMaximumSize(QtCore.QSize(100, 40))
        self.apply_overtime.setObjectName(_fromUtf8("apply_overtime"))
        self.horizontalLayout_7.addWidget(self.apply_overtime)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.widget2 = QtGui.QWidget(self.tab)
        self.widget2.setGeometry(QtCore.QRect(20, 30, 546, 391))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(15)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.widget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(40, 30))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.query_fromdate = QtGui.QDateEdit(self.widget2)
        self.query_fromdate.setMinimumSize(QtCore.QSize(0, 30))
        self.query_fromdate.setMaximumSize(QtCore.QSize(16777215, 30))
        self.query_fromdate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.query_fromdate.setObjectName(_fromUtf8("query_fromdate"))
        self.horizontalLayout_4.addWidget(self.query_fromdate)
        self.label_6 = QtGui.QLabel(self.widget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(30, 30))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setMidLineWidth(0)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.query_todate = QtGui.QDateEdit(self.widget2)
        self.query_todate.setMinimumSize(QtCore.QSize(0, 30))
        self.query_todate.setMaximumSize(QtCore.QSize(16777215, 30))
        self.query_todate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.query_todate.setObjectName(_fromUtf8("query_todate"))
        self.horizontalLayout_4.addWidget(self.query_todate)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.widget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(80, 0))
        self.label_7.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.query_project = QtGui.QComboBox(self.widget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.query_project.sizePolicy().hasHeightForWidth())
        self.query_project.setSizePolicy(sizePolicy)
        self.query_project.setMinimumSize(QtCore.QSize(0, 30))
        self.query_project.setMaximumSize(QtCore.QSize(16777215, 30))
        self.query_project.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.query_project.setObjectName(_fromUtf8("query_project"))
        self.query_project.addItem(_fromUtf8(""))
        self.horizontalLayout_5.addWidget(self.query_project)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_12 = QtGui.QLabel(self.widget2)
        self.label_12.setMinimumSize(QtCore.QSize(0, 0))
        self.label_12.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_8.addWidget(self.label_12)
        self.query_subproject = QtGui.QComboBox(self.widget2)
        self.query_subproject.setMinimumSize(QtCore.QSize(0, 30))
        self.query_subproject.setObjectName(_fromUtf8("query_subproject"))
        self.query_subproject.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.query_subproject)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.label_15 = QtGui.QLabel(self.widget2)
        self.label_15.setText(_fromUtf8(""))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_4.addWidget(self.label_15)
        self.label_14 = QtGui.QLabel(self.widget2)
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_4.addWidget(self.label_14)
        self.label_13 = QtGui.QLabel(self.widget2)
        self.label_13.setText(_fromUtf8(""))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_4.addWidget(self.label_13)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_17 = QtGui.QLabel(self.widget2)
        self.label_17.setText(_fromUtf8(""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_9.addWidget(self.label_17)
        self.query = QtGui.QPushButton(self.widget2)
        self.query.setMinimumSize(QtCore.QSize(100, 40))
        self.query.setObjectName(_fromUtf8("query"))
        self.horizontalLayout_9.addWidget(self.query)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "加班申请", None))
        self.name.setText(_translate("MainWindow", "姓名", None))
        self.name_edit.setText(_translate("MainWindow", "编辑", None))
        self.dep.setText(_translate("MainWindow", "部门", None))
        self.dep_line.setItemText(0, _translate("MainWindow", "三维动画", None))
        self.dep_line.setItemText(1, _translate("MainWindow", "投标动画", None))
        self.dep_line.setItemText(2, _translate("MainWindow", "二维动画", None))
        self.dep_line.setItemText(3, _translate("MainWindow", "平面设计", None))
        self.dep_line.setItemText(4, _translate("MainWindow", "编导", None))
        self.dep_edit.setText(_translate("MainWindow", "编辑", None))
        self.label.setText(_translate("MainWindow", "加班日期", None))
        self.apply_date.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.label_3.setText(_translate("MainWindow", "加班时长", None))
        self.label_4.setText(_translate("MainWindow", "加班餐", None))
        self.label_2.setText(_translate("MainWindow", "加班项目", None))
        #self.apply_project.setItemText(0, _translate("MainWindow", "*", None))
        self.label_8.setText(_translate("MainWindow", "加班子项目", None))
        #self.apply_subproject.setItemText(0, _translate("MainWindow", "*", None))
        self.label_9.setText(_translate("MainWindow", "描述", None))
        self.desc.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">加班描述</span></p></body></html>", None))
        self.apply_overtime.setText(_translate("MainWindow", "申请加班", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "申请加班", None))
        self.label_5.setText(_translate("MainWindow", "从", None))
        self.query_fromdate.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.label_6.setText(_translate("MainWindow", "至", None))
        self.query_todate.setDisplayFormat(_translate("MainWindow", "yyyy-M-d", None))
        self.label_7.setText(_translate("MainWindow", "查询项目", None))
        self.query_project.setItemText(0, _translate("MainWindow", "*", None))
        self.label_12.setText(_translate("MainWindow", "查询子项目", None))
        self.query_subproject.setItemText(0, _translate("MainWindow", "*", None))
        self.query.setText(_translate("MainWindow", "开始查询", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "查询加班", None))

