# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Dev\overtime-management\ui_memberClient.ui'
#
# Created: Wed Oct 25 23:27:57 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from newTable import * 

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(QtGui.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1600, 800)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 900))
        #MainWindow.setMaximumSize(QtCore.QSize(1600, 900))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setWindowTitle(_fromUtf8("Member Clinet beta v1.0"))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 50, 1580, 840))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.layoutWidget = QtGui.QWidget(self.tab1)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 25, 1560, 780))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tabWidget_2 = QtGui.QTabWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_2 = QtGui.QWidget()
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tab_2.setFont(font)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.layoutWidget1 = QtGui.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(5, 10,1540, 32))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_32 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout.addWidget(self.label_32)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(50, 0))
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.label_tables = QtGui.QLabel(self.layoutWidget1)
        self.label_tables.setObjectName(_fromUtf8("label_tables"))
        font.setPointSize(15)
        self.label_tables.setFont(font)
        self.horizontalLayout.addWidget(self.label_tables)
        self.layoutWidget2 = QtGui.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(5, 50, 1540,700))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_20.setMargin(0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tree_project = QtGui.QTreeWidget(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_project.sizePolicy().hasHeightForWidth())
        self.tree_project.setSizePolicy(sizePolicy)
        self.tree_project.setMaximumSize(QtCore.QSize(250, 16777215))
        self.tree_project.setObjectName(_fromUtf8("tree_project"))
        self.tree_project.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout.addWidget(self.tree_project)
        self.horizontalLayout_20.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.table_prodetail = NewTable(self.layoutWidget2)
        self.table_prodetail.setObjectName(_fromUtf8("table_prodetail"))
        self.table_prodetail.setColumnCount(0)
        self.table_prodetail.setRowCount(0)
        self.table_prodetail.horizontalHeader().setStretchLastSection(True)
        self.table_prodetail.verticalHeader().setVisible(False)
        self.table_prodetail.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.verticalLayout_2.addWidget(self.table_prodetail)
        self.horizontalLayout_20.addLayout(self.verticalLayout_2)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(5, 10, 1540, 740))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        label1 = QtGui.QLabel(u'只显示项目')
        label1.setSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        label2 = QtGui.QLabel(u'只显示展项')
        label2.setSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        label3 = QtGui.QLabel(u'只显示人员')
        label3.setSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        space = QtGui.QLabel('')
        space.setMaximumWidth(30)
        self.combo_scheduleProjectFilter = QtGui.QComboBox(self.layoutWidget_2)
        self.combo_scheduleProjectFilter.setMinimumWidth(200)
        self.combo_scheduleProjectFilter.setObjectName(_fromUtf8("combo_scheduleProjectFilter"))
        self.combo_scheduleSubprojectFilter = QtGui.QComboBox(self.layoutWidget_2)
        self.combo_scheduleSubprojectFilter.setMinimumWidth(200)
        self.combo_scheduleSubprojectFilter.setObjectName(_fromUtf8("combo_scheduleSubprojectFilter"))
        self.combo_scheduleMemberFilter = QtGui.QComboBox(self.layoutWidget_2)
        self.combo_scheduleMemberFilter.setMinimumWidth(200)
        self.combo_scheduleMemberFilter.setObjectName(_fromUtf8("combo_scheduleMemberFilter"))
        self.check_scheduleShowDetail = QtGui.QCheckBox(u'显示详情信息')
        self.check_scheduleShowDetail.setChecked(True)
        self.horizontalLayout_9.addWidget(label1)
        self.horizontalLayout_9.addWidget(self.combo_scheduleProjectFilter)
        self.horizontalLayout_9.addWidget(space)
        self.horizontalLayout_9.addWidget(label2)
        self.horizontalLayout_9.addWidget(self.combo_scheduleSubprojectFilter)
        self.horizontalLayout_9.addWidget(space)
        self.horizontalLayout_9.addWidget(label3)
        self.horizontalLayout_9.addWidget(self.combo_scheduleMemberFilter)        
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_10 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)

        self.horizontalLayout_9.addWidget(self.check_scheduleShowDetail)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.label_19 = QtGui.QLabel(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_9.addWidget(self.label_19)
        self.period_combo = QtGui.QComboBox(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.period_combo.sizePolicy().hasHeightForWidth())
        self.period_combo.setSizePolicy(sizePolicy)
        self.period_combo.setMinimumSize(QtCore.QSize(100, 0))
        self.period_combo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.period_combo.setModelColumn(0)
        self.period_combo.setObjectName(_fromUtf8("period_combo"))
        self.period_combo.addItem(_fromUtf8(""))
        self.period_combo.addItem(_fromUtf8(""))
        self.period_combo.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.period_combo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(1)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.entry_list = QtGui.QTreeWidget(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entry_list.sizePolicy().hasHeightForWidth())
        self.entry_list.setSizePolicy(sizePolicy)
        self.entry_list.setMaximumSize(QtCore.QSize(250, 16777215))
        self.entry_list.setSizeIncrement(QtCore.QSize(0, 0))
        self.entry_list.setBaseSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.entry_list.setFont(font)
        self.entry_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.entry_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.entry_list.setAlternatingRowColors(True)
        self.entry_list.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.entry_list.setIndentation(20)
        self.entry_list.setRootIsDecorated(True)
        self.entry_list.setUniformRowHeights(False)
        self.entry_list.setAllColumnsShowFocus(False)
        self.entry_list.setHeaderHidden(False)
        self.entry_list.setObjectName(_fromUtf8("entry_list"))
        item_0 = QtGui.QTreeWidgetItem(self.entry_list)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.horizontalLayout_21.addWidget(self.entry_list)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.period1_table = NewTable(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.period1_table.sizePolicy().hasHeightForWidth())
        self.period1_table.setSizePolicy(sizePolicy)
        self.period1_table.setMinimumSize(QtCore.QSize(0, 15))
        self.period1_table.setMaximumSize(QtCore.QSize(16777215, 25))
        self.period1_table.setBaseSize(QtCore.QSize(0, 0))
        self.period1_table.setFrameShape(QtGui.QFrame.StyledPanel)
        self.period1_table.setLineWidth(1)
        self.period1_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.period1_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.period1_table.setAutoScrollMargin(16)
        self.period1_table.setWordWrap(True)
        self.period1_table.setCornerButtonEnabled(False)
        self.period1_table.setColumnCount(14)
        self.period1_table.setObjectName(_fromUtf8("period1_table"))
        self.period1_table.setRowCount(0)
        self.period1_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.verticalLayout_11.addWidget(self.period1_table)
        self.period2_table = NewTable(self.layoutWidget_2)
        self.period2_table.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.period2_table.sizePolicy().hasHeightForWidth())
        self.period2_table.setSizePolicy(sizePolicy)
        self.period2_table.setMinimumSize(QtCore.QSize(0, 15))
        self.period2_table.setMaximumSize(QtCore.QSize(16777215, 25))
        self.period2_table.setBaseSize(QtCore.QSize(0, 0))
        self.period2_table.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.period2_table.setLineWidth(1)
        self.period2_table.setMidLineWidth(0)
        self.period2_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.period2_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.period2_table.setAutoScrollMargin(1)
        self.period2_table.setColumnCount(10)
        self.period2_table.setObjectName(_fromUtf8("period2_table"))
        self.period2_table.setRowCount(0)
        self.period2_table.horizontalHeader().setHighlightSections(False)
        self.period2_table.verticalHeader().setVisible(False)
        self.period2_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.verticalLayout_11.addWidget(self.period2_table)
        self.schedule_table = NewTable(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schedule_table.sizePolicy().hasHeightForWidth())
        self.schedule_table.setSizePolicy(sizePolicy)
        self.schedule_table.setBaseSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.schedule_table.setFont(font)
        self.schedule_table.setFrameShadow(QtGui.QFrame.Sunken)
        self.schedule_table.setAutoScroll(False)
        self.schedule_table.setAutoScrollMargin(16)
        self.schedule_table.setAlternatingRowColors(False)
        self.schedule_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.schedule_table.setShowGrid(True)
        self.schedule_table.setGridStyle(QtCore.Qt.DashLine)
        self.schedule_table.setRowCount(10)
        self.schedule_table.setColumnCount(10)
        self.schedule_table.setObjectName(_fromUtf8("schedule_table"))
        self.schedule_table.horizontalHeader().setVisible(False)
        self.schedule_table.horizontalHeader().setHighlightSections(False)
        self.schedule_table.verticalHeader().setVisible(False)
        self.schedule_table.verticalHeader().setStretchLastSection(False)
        self.schedule_table.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.verticalLayout_11.addWidget(self.schedule_table)
        self.horizontalLayout_21.addLayout(self.verticalLayout_11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_21)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        
        self.line_welcom = QtGui.QLabel(self.centralwidget)
        self.line_welcom.setGeometry(QtCore.QRect(10, 15, 176, 26))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.line_welcom.setFont(font)
        self.line_welcom.setObjectName(_fromUtf8("line_welcom"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        #self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.setWindowFlags(Qt.WindowMinMaxButtonsHint)

    def retranslateUi(self, MainWindow):
        self.label_32.setText(_translate("MainWindow", "项目列表", None))
        self.label_tables.setText(_translate("MainWindow", "项目详情", None))
        self.table_prodetail.setSortingEnabled(True)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "详细信息", None))
        self.check_scheduleShowDetail.setText(_translate("MainWindow", "显示详情", None))
        self.label_19.setText(_translate("MainWindow", "显示周期", None))
        self.period_combo.setItemText(0, _translate("MainWindow", "月", None))
        self.period_combo.setItemText(1, _translate("MainWindow", "周", None))
        self.period_combo.setItemText(2, _translate("MainWindow", "日", None))
        self.entry_list.headerItem().setText(0, _translate("MainWindow", "项目列表", None))
        __sortingEnabled = self.entry_list.isSortingEnabled()
        self.entry_list.setSortingEnabled(False)
        self.entry_list.topLevelItem(0).setText(0, _translate("MainWindow", "项目1", None))
        self.entry_list.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "展项1", None))
        self.entry_list.topLevelItem(0).child(0).child(0).setText(0, _translate("MainWindow", "任务1", None))
        self.entry_list.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "展项2", None))
        self.entry_list.topLevelItem(0).child(1).child(0).setText(0, _translate("MainWindow", "任务2", None))
        self.entry_list.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "任务进度", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "项目管理", None))    
        self.line_welcom.setText(_translate("MainWindow", "你好，姚灏", None))

